### ISSUE TITLE
Add labels for partners

### ISSUE THREAD

**Issue by albert12132** [Cal-CS-61A-Staff/ok#252]
For certain projects, we need  a way to label one partner as "partner A" and the other as "partner B". Is there a way to do that on the website?

**Comment by papajohn** [comment]
We were not able to assign per-partner scores this semester. I think we need this feature to grade accurately.

**Comment by alvinwan** [comment]
The front-end is ready. Here is the UI for students:

![site-partner-switch](https://cloud.githubusercontent.com/assets/2068077/8214794/83f6b0a8-14e0-11e5-870f-eebfbbafa81f.gif)

We could run into problems, if students were to switch arbitrarily and get credit for another partner's work. So:

1. At the most basic level, we lock the order if the assignment deadline has passed.
2. To prevent unfairness while the assignment is live, we could do one or more of the following:
	 
	 a. lock 24 hours before it is due
	 b. require confirmation for switch <- this would be unnecessarily ugly though - it would be as, if not more, complicated than group invitations
	 c. allow only the invitation-issuer to switch order

@soumyabasu What do you think? I'm going to implement 1 and 2a, right now, in case we don't think of anything better.

**Comment by alvinwan** [comment]
1. Implemented. Order is locked after deadline passes. (Gray is an assignment past due date)

![site-partner-lock](https://cloud.githubusercontent.com/assets/2068077/8215263/b7709c48-14e3-11e5-8128-c7908c4b4540.gif)

**Comment by papajohn** [comment]
That's nifty!

**Comment by soumyabasu** [comment]
(I, like John, love how it looks! XD)

The main issue I have with locking things is people will inevitably forget to add their partners and many other issues that will need to be taken care of manually by some staff member. I think these issues should be resolved by the lock_date, after which no submissions could be automatically uploaded to OK. So, I think the solution here is to lock partner reordering after the lock_date. (I'm fine with locking any group modifications after the lock date tbh.)

For unfairness while the assignment is live, I think the 'right answer' technically is to have both parties approve the order change. However, in practice that probably won't work out very well since it'll be another round of invitations for them to accept. Since one group member being unfair to another is an issue that will probably end up requiring TA support or the group breaking up, we should probably just leave it alone and assume that both parties are trustworthy.

**Comment by moowiz** [comment]
I agree. I think we should, in general, assume that the students are trustworthy, but make sure that we have a way to deal with them being sneaky, or whatever. I think we've spent a lot of engineering effort thinking about "security issues" which probably haven't even popped up. Or, have they? I'm not sure. I just know we had a lot of these discussions where we were worried about students trying to game the system or whatever. Did stuff like this happen in the past?

**Comment by soumyabasu** [comment]
Most of the security issues have happened at least once and they've gotten caught/handled. But I agree entirely with your general motto of 'assume trustworthiness, but make sure that we can deal with sneakiness'.

**Comment by alvinwan** [comment]
![partner-reorder](https://cloud.githubusercontent.com/assets/2068077/8465662/d3c445e8-2000-11e5-9578-2c67e7133ca1.gif)
