### ISSUE TITLE
Assignment switch when running ok

### ISSUE THREAD

**Issue by papajohn** [Cal-CS-61A-Staff/ok#338]
Would be great to fix this before lab starts tomorrow, if it's really a bug.

While using the ok autograder with lab2, it will initially autograde lab02.py when i type

    python3 ok -q factors

but then if I do it again, it switches to Assignment: Homework 1. Is there any way to fix this?

https://piazza.com/class/i4q8ow8g8bv7oa?cid=176

**Comment by albert12132** [comment]
This is a problem with autoupdating -- it tries to autoupdate to the
current release of OK on github releases, which is compiled with the
config.json for Homework 1.

There are a couple of not-so-easy options to fix this:
* Instead of packaging a config.json with each OK, instead provide a
config.json with the starter files for each assignment and have students
run "ok --config config.json"
* Disable autoupdating. I don't know how to do this.

**Comment by Some3141** [comment]
We should have the config in the zip file and not packaged up with ok, I think.

**Comment by albert12132** [comment]
Sure, we can do that. This will cause a problem with hw1, however, because
students won't have a config.json for hw1. We can have them download it.

**Comment by Some3141** [comment]
We have to tell students about the website anyway, so that should be readily doable.

**Comment by albert12132** [comment]
Actually, this is not preferred, because each assignment's OK can be
compiled with different protocols (e.g. for homeworks, we won't want a
'unlock' protocol, but for projects, we do) and different sources (for
homeworks, we don't need code for loading OkTests, for projects we don't
need code for loading doctests).

We could just include the entire codebase for ok-client, if you don't think
this is a problem.

**Comment by Some3141** [comment]
I think we should since that makes the user experience a little more logical- everything that says 'ok' is the same and the config files are for each assignment. I don't think we're big enough to worry about downloading troubles or something.

**Comment by papajohn** [comment]
I agree that ok should be generic and we should distribute a config.json
file.

Proposed hack to stay compatible with hw 1:
If ok doesn't find a config.json file, then it uses the one that's embedded
within it (which is hard-coded to hw1).

**Comment by albert12132** [comment]
I created [PR](https://github.com/Cal-CS-61A-Staff/ok-client/pull/22) that addresses this.

I'll implement the hack for now, but it should be reverted immediately after homework 1 is due.

**Comment by moowiz** [comment]
Could we maybe include something in the homework python file which would talk to ok and tell it which config to use or something? Or is that a bad idea...
