### ISSUE TITLE
Program or web interface to download all final submissions for an assignment

### ISSUE THREAD

**Issue by papajohn** [Cal-CS-61A-Staff/ok#444]
We need a robust & standard way to download all final submissions for an assignment. (I know @soumyabasu has some kind of script, but let's make sure that the script is sufficiently documented so that exporting submissions is straightforward.

**Comment by jathak** [comment]
I talked with @soumyabasu about adding this to the ok-client. It could then also be used by students to download their latest backup from the server (this might make sharing between partners easier as well). I have a bit of code written for this, but I'd want to see the existing script before proceeding further to make sure I implement it properly.

**Comment by papajohn** [comment]
Adding batch download to `ok-client` sounds like a good idea to me. We need a way to restart a batch download when it's only half-complete and something goes wrong.

**Comment by jathak** [comment]
@soumyabasu, could you upload your script somewhere so I can reference it when implementing this? Thanks!

**Comment by soumyabasu** [comment]
Sent you all of the scripts via email.

The long term solution for using the API is to understand this file: https://github.com/Cal-CS-61A-Staff/ok/blob/master/server/app/api.py

**Comment by jathak** [comment]
I've added this on [this branch](https://github.com/jathak/ok-client/tree/enhancement/jathak/submission-export) where the `--submissions` option overrides the client's normal behavior and instead downloads all  final submissions for the provided assignment (the `--course` option can be used to specify a course ID, though the client will prompt the user to select a course if this isn't provided). It should also be able to resume downloading if something goes wrong.

I don't have automated tests for this yet and I'm not sure how to write them since they depend on a server. I'm also not sure how well this works in relation to partners on an assignment.

**Comment by soumyabasu** [comment]
Nice work- it looks like the right shape. One thing that might get annoying is that we'll have the list of *every* course on ok being displayed all the time. I think your code is laid out well enough though to handle pretty easily.

To test, you should mock out the API calls to the server. Maybe something like [1] might be helpful. Also, you should think of a general way to do this in case someone wants to add a feature like yours and needs to mock out requests to ok-server unless @albert12132 has already done this?

[1] https://pypi.python.org/pypi/requests-mock

**Comment by soumyabasu** [comment]
Oh, one thing- the server might return a permission error, so you should look at the response code and display the right error message. (Imagine if a student tries to download everything)

**Comment by albert12132** [comment]
I'll take a look at this either tonight or tomorrow night. In the meantime,
feel free to make a PR so that we can comment on the code. All of the
current server communication code is untested, so there's not really a good
testing framework set up. I can work with you on developing tests once I
review the code.

**Comment by jathak** [comment]
I have `api_request` displaying `Only members of the course staff can export submissions.` and exiting if it gets a 401 error.

**Comment by soumyabasu** [comment]
Ah, kk. I missed that line- good job. :)

**Comment by albert12132** [comment]
https://github.com/Cal-CS-61A-Staff/ok-client/pull/77 implements a client-based solution to this, although eventually there should be a web interface that supports submission downloads.
