### ISSUE TITLE
Submission search: -onlyfinal false does not work

### ISSUE THREAD

**Issue by albert12132** [Cal-CS-61A-Staff/ok#485]
Doing a submission query with `-onlyfinal false` (one of the example flags) will yield an error. `-onlybackup true` likewise does not work.

**Comment by papajohn** [comment]
It sounds like we need a small test suite against the search utility.

**Comment by alvinwan** [comment]
Just tested it, and it appears to work. Is it possible that the error was for all quoted strings? The latest series of commits fixes quotations.

*My guess is that the search crashed and burned, because the program failed to tokenize a quoted string properly; with an improper assignment name, there would be a floating NoneType object called "assignment" just waiting to kill the program.*

Just `-onlyfinal`:
![admin-search-onlyfinal](https://cloud.githubusercontent.com/assets/2068077/8494392/8cd57b38-2119-11e5-9e23-8fb1c5d40b65.gif)

`-onlyfinal` with a quoted string
![admin-search-onlyfinal-quotes](https://cloud.githubusercontent.com/assets/2068077/8494393/8e977c96-2119-11e5-8a1f-227147404e7e.gif)
