### ISSUE TITLE
Basic Piazza Integration?

### ISSUE THREAD

**Issue by alvinwan** [Cal-CS-61A-Staff/ok#518]
There's an unofficial abstraction for Piazza's API: https://github.com/hfaran/piazza-api What do you guys think about combining this with our soon-to-exist notifications system? Students could view system-issued alerts and (snippets of and links to) pinned Piazza posts in one place. 

This way, we wouldn't need an in-house implementation of "instructor announcements"; it could simply be posted on Piazza and synced to ok automatically.

*No guarantees it'll work. Just wanted to ask if it's worth the time to investigate.

@soumyabasu @Sumukh @papajohn

**Comment by soumyabasu** [comment]
I'm a little nervous about integrating with Piazza to be honest, especially using this API- it doesn't look like a strong codebase.

Also, I think that the instructor announcements for ok would serve a different purpose since students go on Piazza and ok for different reasons. The former is for questions and course information and the latter is to check progress on programming assignments. So, an announcement such as "Your project is due in 4 days!" would go on ok and the course website, but might not belong on Piazza. Whereas something like "Here are some hints for question 5" would go on Piazza and not ok.

But I'm not strongly against the concept of Piazza and ok being more tightly integrated, so if the codebase issue is worked out, I'm fine with it.

**Comment by alvinwan** [comment]
I see - I never actually considered that division of purpose. Does anyone else want to weigh in on this? Otherwise, I'll close this issue until I can think of an appropriate way to connect the two.

**Comment by papajohn** [comment]
Let's not integrate more deeply with Piazza for now. I need to think about
that a little more.

**Comment by alvinwan** [comment]
Sounds good. It can wait.
