### ISSUE TITLE
OK website has unenrolled students and staff

### ISSUE THREAD

**Issue by albert12132** [Cal-CS-61A-Staff/ok#533]
It seems like students and staff members are no longer enrolled in any courses. I'm also no longer able to access the `manage` page with my admin account.

**Comment by Sumukh** [comment]
Looking into this - it's related to the `is_admin` check on users.

**Comment by Sumukh** [comment]
Found the issue and deployed a temporary fix in e81fdfa08be57ea42173cff82ba8f584cac55991

A few issues here - 
1) we added a new field to the user lookup process without first having an index for it. 
This caused any submissions or website requests to fail because app engine wasn't able to process the query in the lookup until the index fully generated. 
2) Not all users have a status attribute - (aprox. 50 users) so we can't introduce code that assumes all users have a status. For most pre-existing users, status is NULL. I'm not sure where in the process this would be changed for users.

**Comment by albert12132** [comment]
It seems like some students are still having this issue, as of 8 minutes ago. See https://piazza.com/class/i9yw3s5t8k63ge?cid=314

**Comment by alvinwan** [comment]
On the way home. I'll get on it once as soon as I can and post hotfix updates here.

**Comment by soumyabasu** [comment]
Don't push/deploy anything yet.

**Comment by Sumukh** [comment]
@alvinwan - we've found the issue - there are duplicate users as a result of #534 - check your chat.

**Comment by alvinwan** [comment]
Sumukh and Soumya fixed it; they went through and deleted the ~50 duplicate users.
