### ISSUE TITLE
Student cannot view submission on OK

### ISSUE THREAD

**Issue by robhuang** [Cal-CS-61A-Staff/ok#543]
Student submitted hw04, can view submission on the ok course page, but after clicking on it, she receives an error: key 4973004870123520 not found.

Piazza post [@314](https://piazza.com/class/i9yw3s5t8k63ge?cid=314). See followups.

![ok_hw04_02](https://cloud.githubusercontent.com/assets/3672232/8643273/873861ca-28e6-11e5-9497-09ac623fe51f.PNG)

**Comment by albert12132** [comment]
Just to clarify, on the main student view, the assignment reports that a submission was made. However, when clicking the "View submission" button in the side bar, the error that @robhuang posted occurs.

**Comment by robhuang** [comment]
We are able to search for the submission and view it, but the normal "View submission" button still breaks.

**Comment by alvinwan** [comment]
I have an idea why it might happen; I'll work on it in the morning.

**Comment by alvinwan** [comment]
I tried it locally and can't replicate this problem; I'm hoping it's because master simply hasn't been deployed yet. @Sumukh Could that be it? If the deployment is synced... I'll need to keep trying. 

@robhuang Is this what you mean? (This is the latest version of master and may not be deployed yet.)
![Uploading access-subm.gif…]()


@albert12132 Can I have access to the Piazza?

**Comment by Sumukh** [comment]
Deployed.
