### ISSUE TITLE
Submission Downloads too big

### ISSUE THREAD

**Issue by alvinwan** [Cal-CS-61A-Staff/ok#557]
Jeffrey

> When trying to download OK submissions from a search query, I just get the message:
>Success

>Saving submissions to /ok_grades_bucket/query_greynotgray-berkeley-edu_2015-07-31-21-18-53-167770.zip
Zip of submissions will be ready in Google Cloud Storage ok_grades_bucket in a few minutes

>Along with a link to view the zip (https://console.developers.google.com/storage/browser/ok_grades_bucket/query_greynotgray-berkeley-edu_2015-07-31-21-18-53-167770.zip).  But after a few minutes, when I click the link, I just get a message that just says "Failed to load".  Although for Albert, the message he gets is "no objects in this bucket".  I think for me, I might be having a permissions error, but we don't have a way to download submissions for project 3.

Sumukh

>I remember seeing a timeout error on the deferred write to the bucket in the logs. That seems like it could be the culprit. 

Idea: split up zip generation into subprocesses, download actually spawns one task per page of download

**Comment by Sumukh** [comment]
So the timeout is supposedly 10 minutes for task queue based jobs (which deferred uses) - ([App Engine Docs]) - which makes me think this should be solvable within App Engine for most downloads (except perhaps extremely large downloads of backups). 

I'm not sure if we should go through a lot of trouble to support these kinds of downloads. I struggle to see a case where you really want every backup/submission ever made - other than accidental clicks of the download button. 

I propose that we wait until we see this issue pop-up again and we will build this integration into the autograder/ok. If it's actually the case that 10 minutes isn't enough time for a 1000+ student final_submission download, we'll have to integrate the autograder. 

The things that would have to be built: 
- [ ] Autograder: Ok Integration has a download to zip endpoint. 
- [ ] Autograder: Writes to GCS & sends email (email notifications will be a feature of the autograder) 
- [ ] OK: Send Subm/Backup IDs to Autograder instead of doing a deferred job. 

[Source]: https://cloud.google.com/appengine/articles/deadlineexceedederrors?hl=en

**Comment by alvinwan** [comment]
That's reasonable. I can add a email utility soon, as it's looking more and more like we'll need one.

I'll close this for now then, and we can resurrect it another day.

**Comment by Sumukh** [comment]
Just took a look at the logs - it seems like even a simple search for a project final submissions fails. Interestingly it fails on the query part. 

Using cursors for this query should help. http://stackoverflow.com/questions/2953419/is-it-possible-to-increase-the-response-timeout-in-google-app-engine/11787275#11787275

**Comment by alvinwan** [comment]
Darn. I'll work on it tomorrow.
