### ISSUE TITLE
assignment detail view

### ISSUE THREAD

**Issue by alvinwan** [Cal-CS-61A-Staff/ok#581]
<img width="862" alt="screen shot 2015-08-31 at 9 09 33 am" src="https://cloud.githubusercontent.com/assets/2068077/9583437/2d0ba030-4fc0-11e5-9fc6-6124d1bc79b0.png">

**Comment by alvinwan** [comment]
@Sumukh I didn't test after adding the permissions check... as I should've done. I just pushed a fix to master though, could you take a look/deploy so Prof. DeNero can use it?

**Comment by Sumukh** [comment]
I tested & fixed the issue last night in https://github.com/Cal-CS-61A-Staff/ok/commit/1dc0ecfef951902eb2be20bddf7e7bab7c48f25a before deploying. 

This commit (6ff10bc) reintroduces the bug because now the permission check references the undefined `assignment` error. I'll fix this for consistency and then we should be set. Either way the page should work as deployed right now.

**Comment by alvinwan** [comment]
hold on - we should just make it `obj` then - previously, the param passed to `can` was `obj` instead of `assignment`. In both cases, there was a rogue, undefined variable.

**Comment by Sumukh** [comment]
Yup! It should already be in my latest commit. f5a08568dd721aae532e1e51e5c3a4ac68cfde40

**Comment by alvinwan** [comment]
Oh, cool x) didn't see that my bad. Sounds good.
