### ISSUE TITLE
Ok V3 Rewrite 

### ISSUE THREAD

**Issue by Sumukh** [Cal-CS-61A-Staff/ok#632]
Let's put rewrite related comments in this issue. The branch is `rewrite/sumukh/v3` 

 - Design doc [here](https://docs.google.com/document/d/1idQsvWu8quDRqXmcGL-7ZqAd-GpAbCY0uaa0he95lm4/edit?usp=sharing)

-  [Current Documentation](http://cal-cs-61a-staff.github.io/ok/) (hosted on gh-pages for now, only has some info about models)

Major Changes: 
- Move off of GAE
- Frontend will be rendered server side
- Model changes (see documentation link above) 

Help Wanted: 
- TODOs will be listed below. 
- Feel free to dive in

Comments wanted: 
- Model design. Does it make sense? Can it be improved?
- Overall Comments are welcome. 

TODOs: 

Feel free to claim any of these by editing and putting your name next to it

- [x] Documentation Setup 
- [x] Design Doc 
- [x] API for Ok-Client Submission
- [x] Localhost Authentication
- [x] Better Secret Management
- [x] Enrollment API for ok-client
- [x] Frontend layout  
- [x] Integrate Student Frontend
- [x] Admin Layout
- [x] Enrollment Page for staff
- [ ] Permissions for models
- [ ] Port GCS code from v1
- [ ] Export of all student submissions to zip  
- [ ] Export of scores on an assignment to CSV
- [ ] Better Diff Generation 
- [ ] Admin Side Student View (type in a student get all of their progress/activity and change things)
- [x] Forms for admin interface. 
- [x] Frontend code for Github like diffs (Brian)
- [ ] Experiment with Kubernetes for deployment 
- [ ] Load Test

**Comment by Sumukh** [comment]
TODOs: 

Feel free to claim any of these by editing and putting your name next to it

- [x] Documentation Setup 
- [x] Design Doc 
- [x] API for Ok-Client Submission
- [ ] Enrollment API for ok-client (@alvinwan? - the url can be `/api/v3/enrollment`) 
- [ ] Frontend layout 
- [ ] Admin Layout
- [ ] Permissions for models 
- [ ] Port GCS code from v1
- [ ] Better Diff Generation 
- [ ] Forms for admin interface. 
- [ ] Frontend code for Github like diffs (@alvinwan?)
- [ ] Experiment with Kubernetes for deployment

**Comment by knrafto** [comment]
Having the backend ready by 1/15 seems quite ambitious. We can potentially still use it this semester if we have a way we move data from v2 ok to v3 ok.

I like the generated documentation - very pretty, a huge improvement.

Some suggestions:

* A better name! Don't really have any suggestions, but I'm fine with calling it "the autograder" or something
* No explicit final submissions. All submissions are autograded, and the "final" submission is the latest submission that received the highest score. This is how the 162 autograder works, and it offers several advantages:
  * No guessing whether submitting late with the late penalty will help you or hurt you
  * No fear of a partner accidentally submitting an old version
  * Seeing the server score (almost) immediately so there's no surprises (especially with hidden tests)
* Submissions and backups should be immutable. In particular, there should be no "queue" or "revision" columns.
  * Instead of queues, have some mechanism to assign graders to submissions. A grader's "queue" is all submissions that have been assigned to them. I haven't really thought about this too much.
  * For revisions, the autograder can look for the first submission after some timestamp and award it full composition points automatically. The grader's score will now be ignored, since we'll take the max composition score awarded for any submission.
* In fact, submissions don't contain any data other than a backup; so instead we can just have a Boolean in the Backup model that says whether it's a submission.
* Tagging backups/submissions with groups instead of users might get confusing. e.g. partner A submits; partner B accepts invitations, but can't see partner A's submission
* GroupMember is a great idea, so group members will actually be queryable.
* Groups and GroupMembers should never be deleted, so we can track history. A user's a group is the most recent group that they are an active member of. It's also much easier to reason about consistency this way.
* One-element groups are perfectly fine. If a user does not have a group, treat it the same as if they were in a one-element group.

Proposed model changes:
```
class Backup(db.Model, TimestampMixin):
    id = db.Column(db.Integer(), primary_key=True)
    messages = db.relationship("Message")
    scores = db.relationship("Score")
    client_time = db.Column(db.DateTime())
    submitter = db.Column(db.ForeignKey("user.id"), nullable=False)
    assignment = db.Column(db.ForeignKey("assignment.id"), nullable=False)
    submission = db.Column(db.Boolean())

# No Submission or FinalSubmission

class Group(db.Model, TimestampMixin):
    id = db.Column(db.Integer(), primary_key=True)
    assignment = db.Column(db.ForeignKey("assignment.id"), nullable=False)
    members = db.relationship("GroupMember")

class GroupMember(db.Model, TimestampMixin):
    id = db.Column(db.Integer(), primary_key=True)
    user = db.Column(db.ForeignKey("user.id"), nullable=False)
    group = db.Column(db.ForeignKey("group.id"), nullable=False)
    pending = db.Column(db.Boolean())  # True if invitation; False if active
```

**Comment by knrafto** [comment]
A good way to test is by randomly generating data, and testing properties; similar to QuickCheck, ScalaCheck, etc.

**Comment by alvinwan** [comment]
Comments on the model:

FinalSubmission:
- I think its better to leave the FS table out. It was a hassle trying to access submission code (FS -> Submission -> Backup). Per Kale's suggestion above, I also agree with compacting the three tables - FS, Submission, Backup - into one. We should add a boolean field for `is_final` as well.

GroupMember: yes!

Queue: (re: kale)
I agree. Instead of Queue, we can just have a many-to-many `GradingAssignments`? Although, that's a  rather hefty name:
```
class GradingAssignments(db.Model, TimestampMixin):
    id = db.Column(db.Integer(), primary_key=True)
    user = db.Column(db.ForeignKey("user.id"), nullable=False)
    backup = db.Column(db.ForeignKey("backup.id"), nullable=False)
    score = db.Column(db.ForeignKey("score.id"), nullable=True)
```

Alternate Emails:
We could use a one-to-many:

```
class Emails(db.Model, TimestampMixin):
    id = db.Column(db.Integer(), primary_key=True)
    user = db.Column(db.ForeignKey("user.id"), nullable=False)
    email = db.Column(db.String())
    is_primary = db.Column(db.Boolean())
```

Submissions -> Groups (instead of Users)
I'm ambivalent about this only because both implementations present significant challenges.

Miscellaneous comments:

- Auto grading (re: kale) I think auto grading submissions as they come in is ideal, but with 1400+ students, I don't know if that'd be feasible. I agree it'd be nice, and it's definitely worth exploring, though.
- I can work on the Enrollment API, frontend layout/code for now. I'll get that wrapped up.
- 1/15 is definitely ambitious. I'm up for it. :P

**Comment by knrafto** [comment]
Maybe we can do some back-of-the-envelopes here - how many submissions (not backups) does the backend get during peak times? How many submissions can one autograder instance handle?

Also, I'm Kyle :)

**Comment by knrafto** [comment]
@alvinwan 
> Submissions -> Groups (instead of Users)
I'm ambivalent about this only because both implementations present significant challenges.

what are the significant challenges of each?

**Comment by alvinwan** [comment]
Oops, sorry Kyle :P

If submissions are associated with users:
- finding all submissions that a user can access is expensive and unwieldy
- it's clearer who contributed what to the codebase

If submissions are associated with groups:
- users lose all submissions when they leave a group
- querying by user and group is cleaner, because it's just querying by group

After looking at it, I suppose the latter is a much worse problem.

re: autograder
Good idea. I'll see if I can navigate the app engine console to find data. I bring this up, because it ended up being problematic for 61B, which had several hundred fewer students and the same model of instant-autograding.

**Comment by Sumukh** [comment]
Thanks for all of the comments. I'll go through them soon. 

The single table approach for backups is what we originally had (see #330 for when we created submissions) and #286 for Final Submission. 

I think it became hard to query because:
- the Backups table was large (it stored all of the messages)
- the submit property was stored in the messages (making it hard to query on/index) 

Having the student being able to flag a submission is a requirement for some classes (CS168). I really like the idea of students being able to tell us what submission they want graded. I think having students being able to choose a submission is a must have feature - otherwise Ok would force instructors to have a certain policy. A `flagged` property might be able to enforce this. 

- I'd still like to keep the `Submission` table in for now (but keep it to assignment, user, backup, timestamp, flagged)
- FinalSubmission can be ditched with the "Flagged" property. 
- We will only have to modify the table in two places (new submissions from the API and the "Mark as Final" button on the front-end) 
- I think it'll make certain queries slightly faster (and we can measure if it does once we get some data) 
- Once we have some real data in there we can see if we can drop it without any performance impacts

Here are some approximate numbers from the datastore
Backups: `5.5M`
Submissions: `200,000` 
FinalSubmissions: `63425` 

Each level brings us down an order of magnitude which makes it easier for us to query on. 

I'm not too concerned about the autograder since it can scale easily (upto ~80 submissions/second) - though we would be putting quite a bit of load on it (especially if we have continuous grading with autograder only tests because students will submit more often). With continuous grading - we'd automatically grade all submissions

Hog Submissions: ~3877
Scheme: ~7000 (only ~800 FS so ~9 submissions/group) 

One of the nice things is that migrations will be a lot easier so model changes aren't as big of a hassle. 

@papajohn + @soumyabasu - Thoughts on removing the `Submission/FinalSubmission` model (and other comments) ?

**Comment by papajohn** [comment]
I don't think I'll be able to review all these changes in the next week,
but feel free to figure it out yourselves and ping me if you need my input
on something specific.

The backup/submission/final-submission system has seemed to be very helpful
for performance, but I agree that submission shouldn't need to exist since
it's effectively just an index on a field about a backup. Perhaps if you're
switching the back-end to some SQL implementation, keeping a separate table
for submissions is unnecessary.

You don't want FinalSubmissions to be a field of a backup because then you
can't structurally enforce the one-final-submission-per-user property. If
it's a separate table, you can have a unique key for (user, submission)
pairs that links to the chosen backup.

(Also, I think the name is ok.)

-John

**Comment by knrafto** [comment]
Closed in favor of more granular issues
