### ISSUE TITLE
Extensions for students

### ISSUE THREAD

**Issue by knrafto** [Cal-CS-61A-Staff/ok#710]
Instead of checking timestamps. Used for extensions

**Comment by Sumukh** [comment]
This needs an interface that instructors can use - which depends on some kind of instructor view of students.

**Comment by Sumukh** [comment]
I'm thinking of having an Extensions table and an interface on the Admin side to manage them. Students would also see that they have an extension. 

Instructions can grant a student an extension for a specific assignment. 
(for example, Grant extension to student@example.com for Hog until 2/3/16 11:59:59 PM) 

- Extensions apply to all members of the group (If you are in a group with a user who is currently has an extension) 
- An extension may be modified, but only one row in the table will exist for user.id, assignment.id
- Extensions have the following actions: 
   - The `late` column on score exports returns False for backups submitted past the deadline but before the extension expiration. 
   - If the extension is past the `lock_date` - It allows that student to continue submitting. 
   - If continuous autograding is enabled, that will also be triggered.

@knrafto, @papajohn: Thoughts on this approach to extensions? Anything I'm forgetting? 

Details: 

To handle composition grading for extensions: 
- The instructor dashboard for extensions will display extensions that are "completed" and scores can be manually tweaked from there. 

As for early deadlines for grading: 
- I might leave that up to the autograding script. The API can provide the details of the extensions. 

Logging/Permissions: 
- Log details so that extensions are auditable. The TA, Instructors roles can create extensions

Autograding script changes:
 - Instead of manually calculating whether the submission is late, the API will provide `is_late`. 

Future Plans: 
- Once we have a workflow to autograde a single submission, that will also be an action 
- I'm not planning on allowing group creations after the deadline

**Comment by knrafto** [comment]
Seems like a good idea to me. For composition grading, a late submission should just show up as an unassigned grading task (it might automatically already?) instead of doing anything special in the extensions interface. Then we can just hit "Assign Grading" and all is well.

Nitpick: The API property should be called `late` instead of `is_late` for consistency with `flagged` and `submit`

**Comment by Sumukh** [comment]
Resolved in #1086
