### ISSUE TITLE
Add backup for submissions

### ISSUE THREAD

**Issue by moowiz** [Cal-CS-61A-Staff/ok#77]
I'm worried about a bug in our program wiping our submissions. Should we backup our data?

I'm pretty sure that if you delete something in GAE, it's gone, and you can't get it back.

**Comment by papajohn** [comment]
Did we ever learn how to back up?

**Comment by alvinwan** [comment]
Looking at the documentation right now - seems doable.. just a step-by-step process to follow. I could get the backups started, but I don't have access to GAE.

**Comment by soumyabasu** [comment]
I think @moowiz and I were talking about this at one point and it seems like if the backup goes wrong, really bad things might happen. (Especially since that's a beta feature.)

One hacky way to backup would be to use an API call from an external service to periodically call into ok and get submissions and so on.

**Comment by alvinwan** [comment]
Mhm, that's a good point. Should I nose around for another service like that one then? Or should we code an in-house solution.

**Comment by papajohn** [comment]
We don't need to worry about replicating outside of the datastore. We
should just focus on making the system robust to administrator error.
Perhaps the User & FinalSubmission tables should be duplicated into
additional datastore tables.

**Comment by alvinwan** [comment]
Sounds good. I will work on that.

**Comment by alvinwan** [comment]
Backup completed in GAE.
